--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/png-converter
branches:
  - main
projects:
  png-converter:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: PresentKim/arrayutils/arrayutils
        version: ^4.0.0
...
